CHECK_NOW = 'Проверить сейчас'
USER_ADDED = 'Пользователь {user_id} добавлен в рассылку.'
USER_ALREADY_ADDED = 'Пользователь уже добавлен в рассылку.'
ALL_HOSTS_UP = 'Все хосты доступны.'
FOLLOWING_HOSTS_DOWN = 'Следующие хосты не отвечают:\n'